SKILL_VOCABULARY = {
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "git",
    "github",
    "linux",
    "react",
    "angular",
    "vue",
    "spring boot",
    "django",
    "flask",
    "fastapi",
    "machine learning",
    "artificial intelligence",
    "pytorch",
    "tensorflow",
    "ci/cd",
}